# Generated by Django 4.2 on 2023-05-08 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="account",
            new_name="user",
        ),
    ]
