# Generated by Django 4.2 on 2023-05-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products",
            "0002_alter_product_options_product_account_product_name_and_more",
        ),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="order",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="products.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PEDIDO REALIZADO", "Realizado"),
                    ("EM ANDAMENTO", "Andamento"),
                    ("ENTREGUE", "Entregue"),
                ],
                default="PEDIDO REALIZADO",
                max_length=20,
            ),
        ),
    ]
