# Generated by Django 4.2 on 2023-05-08 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_order_account_order_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
    ]
