# Generated by Django 4.2 on 2023-05-08 13:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), size=None
                ),
                default=["one", "two", "three"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
