# Generated by Django 4.2 on 2023-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.JSONField(default={"key": "value"}),
            preserve_default=False,
        ),
    ]
