# Generated by Django 4.2 on 2023-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
